import * as R from './4did-lite.js';
import {createStore,parseCoordinates,normalizeGeoJSON,EXAMPLES,sampleDistrict,MAX_FILE_BYTES} from './globe-model.js?v=20260906c';
const $=id=>document.getElementById(id);
const C=window.Cesium;
let storage;try{storage=window.localStorage;}catch{storage={getItem(){throw new Error('Storage blocked');}};}
const store=createStore({storage,mint:R.mintId,zoneOf:R.zoneOf});
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
let viewer=null,selected=null,busy=false,gridOn=false,pickOn=false,is2D=false,gridTimer=null,lastSearch=0;
const points=new Map(),cells=[];
function announce(message,target='searchStatus',error=false){const el=$(target);el.textContent=message;el.dataset.state=error?'error':'success';}
function storageNote(){return store.warning()?` ${store.warning()}`:'';}
function duration(n=1.5){return reduceMotion?0:n;}
function redraw(){viewer?.scene.requestRender();}
function home(){if(!viewer)return;viewer.camera.flyTo({destination:C.Cartesian3.fromDegrees(-30,25,19e6),orientation:{heading:0,pitch:-C.Math.PI_OVER_TWO,roll:0},duration:duration(1.6)});}
function focus(entity){if(!viewer)return;viewer.camera.flyTo({destination:C.Cartesian3.fromDegrees(entity.lng,entity.lat,2400),orientation:{heading:0,pitch:-C.Math.PI_OVER_TWO,roll:0},duration:duration()});}
function fit(){if(!viewer)return;const list=store.all();if(!list.length){home();return;}if(list.length===1){focus(list[0]);return;}const sphere=C.BoundingSphere.fromPoints(list.map(e=>C.Cartesian3.fromDegrees(e.lng,e.lat)));viewer.camera.flyToBoundingSphere(sphere,{duration:duration(),offset:new C.HeadingPitchRange(0,-C.Math.PI_OVER_TWO,Math.max(2200,sphere.radius*3))});}
function drawPoint(entity){if(!viewer||points.has(entity.id))return;const p=viewer.entities.add({id:entity.id,position:C.Cartesian3.fromDegrees(entity.lng,entity.lat,25),point:{pixelSize:9,color:C.Color.fromCssColorString('#4dd0c4'),outlineColor:C.Color.fromCssColorString('#092f31'),outlineWidth:3,scaleByDistance:new C.NearFarScalar(2000,1.2,1e7,.7)},label:{text:entity.labels[0]?.text||'Named place',show:false,font:'12px Inter, sans-serif',fillColor:C.Color.WHITE,showBackground:true,backgroundColor:C.Color.fromCssColorString('#101a29eb'),backgroundPadding:new C.Cartesian2(10,6),pixelOffset:new C.Cartesian2(0,-24),distanceDisplayCondition:new C.DistanceDisplayCondition(0,2e6)}});points.set(entity.id,p);redraw();}
function select(entity,state='Identity selected',fly=false){selected=entity;for(const [id,p] of points){p.label.show=id===entity.id;p.point.pixelSize=id===entity.id?14:9;p.point.color=C.Color.fromCssColorString(id===entity.id?'#eaf1f8':'#4dd0c4');} $('identityPanel').hidden=false;$('identityState').textContent=state;$('identityName').textContent=entity.labels[0]?.text||'Named place';$('identityId').textContent=entity.id;$('identityCoords').textContent=`${entity.lat.toFixed(5)}, ${entity.lng.toFixed(5)}`;$('identityCell').textContent=entity.anchor.cell;$('identityZone').textContent=entity.zone;$('contextJson').textContent=JSON.stringify(store.context(entity.id),null,2);for(const button of $('entityList').querySelectorAll('button'))button.setAttribute('aria-pressed',String(button.dataset.id===entity.id));redraw();if(fly)focus(entity);}
function refresh(){const all=store.all();$('count').textContent=`${all.length} ${all.length===1?'identity':'identities'}`;$('emptyState').hidden=all.length>0;$('exportBtn').disabled=!all.length;$('clearBtn').disabled=!all.length;$('entityList').replaceChildren();for(const entity of all.toReversed?all.toReversed():[...all].reverse()){const button=document.createElement('button');button.type='button';button.className='gx-saved';button.dataset.id=entity.id;button.setAttribute('aria-pressed',String(entity.id===selected?.id));const name=document.createElement('span');name.textContent=entity.labels[0]?.text||'Named place';const coords=document.createElement('small');coords.textContent=`${entity.lat.toFixed(3)} / ${entity.lng.toFixed(3)}`;button.append(name,coords);button.addEventListener('click',()=>select(entity,'Resolved from your collection',true));$('entityList').append(button);}redraw();}
function revealIdentity(){const panel=$('identityPanel'),sidebar=document.querySelector('.gx-sidebar');if(innerWidth>820){sidebar.scrollTo({top:sidebar.scrollTop+panel.getBoundingClientRect().top-sidebar.getBoundingClientRect().top-18,behavior:reduceMotion?'auto':'smooth'});}else panel.scrollIntoView({block:'nearest',behavior:reduceMotion?'auto':'smooth'});}
$('locateBtn').addEventListener('click',()=>{if(selected)focus(selected);if(innerWidth<=820)$('globe').closest('.gx-map').scrollIntoView({block:'start',behavior:reduceMotion?'auto':'smooth'});});
function create(input,{fly=true}={}){const result=store.add(input);drawPoint(result.entity);refresh();select(result.entity,result.existing?'Same identity · resolved':'Identity created',fly);scheduleGrid();revealIdentity();announce((result.existing?'Resolved the existing name. No duplicate created.':'Created a persistent name in your globe sandbox.')+storageNote());return result;}
function setBusy(value){busy=value;$('mintBtn').disabled=value;$('resolveBtn').disabled=value;document.querySelectorAll('[data-example]').forEach(b=>b.disabled=value);$('mintBtn').querySelector('span').textContent=value?'Finding place…':'Create identity';}
async function geocode(address){const wait=Math.max(0,1100-(Date.now()-lastSearch));if(wait)await new Promise(r=>setTimeout(r,wait));lastSearch=Date.now();const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),12000);try{const response=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q='+encodeURIComponent(address),{headers:{Accept:'application/json'},signal:controller.signal});if(!response.ok)throw new Error('Address search is unavailable. Try a latitude, longitude pair or an example place.');const list=await response.json();if(!list.length)throw new Error('No address found. Add a city or country, or enter latitude, longitude.');const p=list[0];return {lat:Number(p.lat),lng:Number(p.lon),label:p.display_name?.split(',').slice(0,2).join(',')||address};}catch(error){if(error.name==='AbortError'||error instanceof TypeError)throw new Error('Address search could not connect. Coordinates and example places still work.');throw error;}finally{clearTimeout(timeout);}}
$('mintForm').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const query=$('addr').value.trim();if(!query){announce('Enter an address or latitude, longitude first.','searchStatus',true);$('addr').focus();return;}setBusy(true);try{const existing=store.find({id:query})||store.find({registry:'address',external_id:query})||store.find({registry:'coordinates',external_id:query})||store.find({registry:'globe.example',external_id:query});if(existing){select(existing,'Same identity · resolved',true);announce('Resolved the existing name. No duplicate created.');return;}const coords=parseCoordinates(query);if(coords){create({...coords,label:`${coords.lat.toFixed(4)}, ${coords.lng.toFixed(4)}`,registry:'coordinates',external_id:query,source:'coordinate entry'});}else{announce('Finding this address with OpenStreetMap…');const place=await geocode(query);create({...place,address:query,source:'OpenStreetMap geocoding'});}}catch(error){announce(error.message,'searchStatus',true);}finally{setBusy(false);}});
$('resolveBtn').addEventListener('click',()=>{const query=$('addr').value.trim();const entity=store.find({id:query})||store.find({registry:'address',external_id:query})||store.find({registry:'coordinates',external_id:query})||store.find({registry:'globe.example',external_id:query});if(entity){select(entity,'Same identity · resolved',true);announce('Found the same identity in your saved globe collection. No new name was created.');}else announce('No saved identity matches. Create it first, or select a place from your collection.','searchStatus',true);});
for(const button of document.querySelectorAll('[data-example]'))button.addEventListener('click',()=>{const key=button.dataset.example;const place=EXAMPLES[key];$('addr').value=place.label;try{create({...place,registry:'globe.example',external_id:place.label,source:'fixed example coordinates'});}catch(error){announce(error.message,'searchStatus',true);}});
$('copyId').addEventListener('click',async()=>{if(!selected)return;try{await navigator.clipboard.writeText(selected.id);announce('Identity copied.');}catch{announce('Copy unavailable here. Select the identity text and copy it manually.','searchStatus',true);}});
function importPoints(points,label,info=''){const results=store.addMany(points);results.forEach(r=>drawPoint(r.entity));refresh();select(results[0].entity,'Collection imported');revealIdentity();fit();scheduleGrid();const added=results.filter(r=>!r.existing).length;announce(`${added} identities added from ${label}.${info}${storageNote()}`,'importStatus');}
$('sampleBtn').addEventListener('click',()=>{try{importPoints(sampleDistrict(),'the synthetic six-place district',' Sample positions are illustrative, not surveyed buildings.');}catch(error){announce(error.message,'importStatus',true);}});
$('uploadBtn').addEventListener('click',()=>$('file').click());
async function importFile(file){if(!file)return;try{if(file.size>MAX_FILE_BYTES)throw new Error('Choose a GeoJSON file smaller than 2 MB.');const data=JSON.parse(await file.text());const result=normalizeGeoJSON(data);importPoints(result.points,file.name,`${result.skipped?` ${result.skipped} unsupported features skipped.`:''}${result.polygons?' Polygons use a representative vertex-mean point, not their full geometry.':''}`);}catch(error){announce(error instanceof SyntaxError?'This file is not valid JSON. Choose a GeoJSON file.':error.message,'importStatus',true);}finally{$('file').value='';}}
$('file').addEventListener('change',event=>importFile(event.target.files[0]));
for(const event of ['dragenter','dragover'])document.addEventListener(event,e=>{if(e.dataTransfer?.types.includes('Files')){e.preventDefault();document.body.classList.add('gx-dragging');}});
document.addEventListener('dragleave',e=>{if(!e.relatedTarget)document.body.classList.remove('gx-dragging');});
document.addEventListener('drop',e=>{if(e.dataTransfer?.files.length){e.preventDefault();document.body.classList.remove('gx-dragging');if(e.dataTransfer.files.length>1){announce('Import one GeoJSON file at a time.','importStatus',true);return;}const detail=$('file').closest('details');if(detail)detail.open=true;importFile(e.dataTransfer.files[0]);}});
$('exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(store.export(),null,2)],{type:'application/geo+json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='4did-globe-identities.geojson';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);announce('Exported your collection as GeoJSON with identity metadata.');});
$('clearBtn').addEventListener('click',()=>{if(!confirm('Clear this globe collection? Export first to keep a copy. Building and ship demo data will not be touched.'))return;store.clear();for(const p of points.values())viewer?.entities.remove(p);points.clear();selected=null;$('identityPanel').hidden=true;refresh();scheduleGrid();announce('Globe collection cleared. Other demos are unchanged.'+storageNote());});
$('flyBtn').addEventListener('click',fit);$('vfit').addEventListener('click',fit);$('vhome').addEventListener('click',home);
$('zin').addEventListener('click',()=>{if(viewer)viewer.camera.zoomIn(Math.max(20,viewer.camera.positionCartographic.height*.4));redraw();});$('zout').addEventListener('click',()=>{if(viewer)viewer.camera.zoomOut(Math.max(20,viewer.camera.positionCartographic.height*.6));redraw();});
$('vnorth').addEventListener('click',()=>{if(!viewer)return;const camera=viewer.camera;camera.flyTo({destination:camera.position.clone(),orientation:{heading:0,pitch:camera.pitch,roll:0},duration:duration(.6)});});
$('v2d').addEventListener('click',()=>{if(!viewer)return;is2D=!is2D;$('v2d').setAttribute('aria-pressed',String(is2D));$('v2d').textContent=is2D?'3D':'2D';if(is2D)viewer.scene.morphTo2D(duration(.8));else viewer.scene.morphTo3D(duration(.8));});
$('pickBtn').addEventListener('click',()=>{if(!viewer)return;pickOn=!pickOn;$('pickBtn').setAttribute('aria-pressed',String(pickOn));$('globe').classList.toggle('gx-picking',pickOn);announce(pickOn?'Click the globe to create an identity at that location.':'Drop-a-pin mode off.');$('sceneStatus').textContent=pickOn?'Click the Earth to name that exact location.':'Explore the globe or select a saved identity.';});
function resForHeight(h){return h>3e6?2:h>1e6?3:h>3e5?4:h>1e5?5:h>3e4?6:h>1e4?7:h>3e3?8:h>1e3?9:10;}
function drawGrid(){if(!viewer)return;for(const e of cells)viewer.entities.remove(e);cells.length=0;if(!gridOn){$('gridInfo').textContent='H3 is the spatial address inside each identity.';redraw();return;}try{const scene=viewer.scene;const center=viewer.camera.pickEllipsoid(new C.Cartesian2(scene.canvas.clientWidth/2,scene.canvas.clientHeight/2),scene.globe.ellipsoid);const carto=center?C.Cartographic.fromCartesian(center):viewer.camera.positionCartographic;const res=resForHeight(viewer.camera.positionCartographic.height);const cell=window.h3.latLngToCell(C.Math.toDegrees(carto.latitude),C.Math.toDegrees(carto.longitude),res);const disk=window.h3.gridDisk(cell,4);const counts=new Map();for(const e of store.all()){const parent=window.h3.cellToParent(e.anchor.cell,res);counts.set(parent,(counts.get(parent)||0)+1);}for(const key of disk){const boundary=window.h3.cellToBoundary(key);const flat=boundary.flatMap(([lat,lng])=>[lng,lat]);const n=counts.get(key)||0;const color=C.Color.fromCssColorString(n?'#4dd0c4':'#7c8cff');const positions=C.Cartesian3.fromDegreesArray(flat);cells.push(viewer.entities.add({polygon:{hierarchy:positions,material:color.withAlpha(n ? .14 : .025),height:5},polyline:{positions:[...positions,positions[0]],width:1,material:color.withAlpha(.5)}}));}$('gridInfo').textContent=`H3 resolution ${res} · ${disk.length} cells around the view center · ${disk.reduce((n,key)=>n+(counts.get(key)||0),0)} identities in these cells`;redraw();}catch{$('gridInfo').textContent='Move the view over the Earth to see its H3 cells.';}}
function scheduleGrid(){if(viewer)$('globe').closest('.gx-map').classList.toggle('gx-detail',viewer.camera.positionCartographic.height<1e6);clearTimeout(gridTimer);gridTimer=setTimeout(drawGrid,150);}
$('gridBtn').addEventListener('click',()=>{if(!viewer)return;gridOn=!gridOn;$('gridBtn').setAttribute('aria-pressed',String(gridOn));drawGrid();});
window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT','BUTTON'].includes(e.target.tagName)||e.target.isContentEditable)return;if(e.key==='Escape'&&pickOn)$('pickBtn').click();if(e.ctrlKey||e.metaKey||e.altKey)return;const id={'+':'zin','=':'zin','-':'zout',h:'vhome',H:'vhome',n:'vnorth',N:'vnorth'}[e.key];if(id){e.preventDefault();$(id).click();}});
function mapFailure(message){$('sceneStatus').textContent=message;$('mapFallback').hidden=false;for(const id of ['zin','zout','vhome','vnorth','v2d','gridBtn','pickBtn','vfit','flyBtn'])$(id).disabled=true;}
$('retryMap').addEventListener('click',()=>location.reload());
async function initMap(){if(!C){mapFailure('The 3D engine could not load. You can still create, resolve, and export identities.');return;}try{
  // Cesium 1.120 uses baseLayer, not the removed imageryProvider viewer option.
  // Explicitly avoid the default ion layer: no access token is required here.
  viewer=new C.Viewer('globe',{baseLayer:false,baseLayerPicker:false,geocoder:false,homeButton:false,sceneModePicker:false,navigationHelpButton:false,animation:false,timeline:false,fullscreenButton:false,infoBox:false,selectionIndicator:false,skyBox:false,requestRenderMode:true,maximumRenderTimeChange:Infinity});
  viewer.resolutionScale=Math.min(window.devicePixelRatio||1,1.5);
  viewer.scene.backgroundColor=C.Color.fromCssColorString('#0b111b');viewer.scene.globe.baseColor=C.Color.fromCssColorString('#102538');viewer.scene.globe.enableLighting=false;
  if(viewer.scene.sun)viewer.scene.sun.show=false;if(viewer.scene.moon)viewer.scene.moon.show=false;viewer.scene.fog.enabled=false;viewer.scene.globe.showGroundAtmosphere=true;
  const overview=await C.SingleTileImageryProvider.fromUrl('assets/globe/earth.jpg',{credit:new C.Credit('Overview: NASA Blue Marble')});
  viewer.imageryLayers.addImageryProvider(overview);
  // Live satellite detail over a local overview layer. A failed tile service
  // never removes the usable overview or disables identity operations.
  const satellite=new C.UrlTemplateImageryProvider({url:'https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',maximumLevel:19,credit:new C.Credit('Satellite imagery © Esri, Maxar, Earthstar Geographics')});
  const layer=viewer.imageryLayers.addImageryProvider(satellite);layer.brightness=.92;layer.saturation=.8;
  let tileFailures=0; satellite.errorEvent.addEventListener(()=>{tileFailures++;if(tileFailures>=3){layer.show=false;$('sceneStatus').textContent='Local NASA overview · satellite detail unavailable';redraw();}});
  $('sceneStatus').textContent='Globe ready · NASA overview + Esri satellite imagery';
  viewer.scene.renderError.addEventListener(()=>mapFailure('The 3D view stopped rendering. Your identity collection is safe; reload to retry.'));
  viewer.scene.globe.tileLoadProgressEvent.addEventListener(()=>redraw());
  viewer.camera.percentageChanged=.1;viewer.camera.changed.addEventListener(scheduleGrid);viewer.camera.moveEnd.addEventListener(scheduleGrid);viewer.scene.morphComplete.addEventListener(scheduleGrid);
  viewer.screenSpaceEventHandler.setInputAction(m=>{if(pickOn){const hit=viewer.camera.pickEllipsoid(m.position,viewer.scene.globe.ellipsoid);if(!hit){announce('Click a location on the Earth, not the space around it.','searchStatus',true);return;}const carto=C.Cartographic.fromCartesian(hit);const lat=C.Math.toDegrees(carto.latitude),lng=C.Math.toDegrees(carto.longitude);const query=`${lat.toFixed(6)}, ${lng.toFixed(6)}`;$('addr').value=query;try{create({lat,lng,label:`Dropped pin · ${lat.toFixed(3)}, ${lng.toFixed(3)}`,registry:'coordinates',external_id:query,source:'globe click'},{fly:false});$('sceneStatus').textContent='Pin named · identity saved in your globe collection';}catch(error){announce(error.message,'searchStatus',true);$('sceneStatus').textContent='Pin could not be named. See the identity controls.';}pickOn=false;$('pickBtn').setAttribute('aria-pressed','false');$('globe').classList.remove('gx-picking');return;}const picked=viewer.scene.pick(m.position);const id=picked?.id?.id;const entity=typeof id==='string'?store.find({id}):null;if(entity)select(entity,'Resolved by shared name');},C.ScreenSpaceEventType.LEFT_CLICK);
  // Suppress the stock double-click tracking animation; retain normal orbit.
  viewer.screenSpaceEventHandler.removeInputAction(C.ScreenSpaceEventType.LEFT_DOUBLE_CLICK);
  store.all().forEach(drawPoint);viewer.camera.setView({destination:C.Cartesian3.fromDegrees(-30,25,19e6),orientation:{heading:0,pitch:-C.Math.PI_OVER_TWO,roll:0}});if(selected)select(selected);drawGrid();redraw();
  new ResizeObserver(()=>{viewer.resize();redraw();}).observe($('globe'));
}catch(error){console.warn('Globe renderer unavailable:',error);mapFailure('The 3D view is unavailable on this browser. Coordinates, examples, and GeoJSON still work.');}}
refresh();if(store.warning())announce(store.warning(),'searchStatus',true);
if(!window.h3){$('mintBtn').disabled=true;$('resolveBtn').disabled=true;announce('The identity library could not load. Reload the page to try again.','searchStatus',true);}
initMap();
